[package]
name = "message_privacy_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.0"
rsa = "0.9.0"
hmac = "0.12.1"
sha2 = "0.10.8"
curve25519-dalek = "4.0.0"
rand = "0.8.5"
base64 = "0.21.0"
